[files]
sources = [{ from = "sources", to = "."}]
files = ["config/{{ terraform_sage_environment }}/{{ variables }}"]
directories = ["config/{{ terraform_sage_environment }}"]
aliases = [
    { variables = "templates/variables.tfvars"}
]

[variables]
terraform_sage_environment = ["dev", "production", "staging"]
