[files]
sources = [{ from = "sources", to = "."}]
generated = ["config/{{ terraform_sage_environment }}/{{ variables }}"]
directories = ["config/{{ terraform_sage_environment }}"]
templates = [
    { variables = "templates/variables.tfvars"}
]

[config]
terraform_sage_environment = ["dev", "production", "staging"]
